### ISSUE TITLE
File variables.data-00000-of-00001 missing

### ISSUE THREAD

**Issue by joern73** [abdur75648/Deep-Learning-Specialization-Coursera#1]
Hello abdur75648 
Thank you for your notebook. Anyway I run into a problem:
In *Deep-Learning-Specialization-Coursera/Convolutional Neural Networks/week3/1 Car_detection (Autonomous_driving)/model_data/*
the file variables.data-00000-of-00001 seems to be missing to restore the trained model.
I get **OpError: model_data/variables/variables.data-00000-of-00001; No such file or directory**
Could you upload it?
Thank you.

**Comment by abdur75648** [comment]
Hey @joern73 
Thank you for your interest.
I am sorry, but I can't upload any (missing) model/dataset here as I don't have the copyright of this specialisation.
The sole purpose of this repository is to be used as a reference by those who get stuck while doing the specialization from Coursera.
